### ISSUE TITLE
current example doesn't work on esp8266

### ISSUE THREAD

**Issue by TarjanPeter** [SpotlightKid/micropython-stm-lib#2]
I'm trying and failing to make your lib work on an esp8266 using this example:

```
 -*- coding: utf-8 -*-

from time import sleep_ms
from encoder import Encoder

def main():
    enc = Encoder(pin_clk=4, pin_dt=5)
    lastval = 0

    while True:
        val = enc.value
        if lastval != val:
            lastval = val
            print(val)
        sleep_ms(50)

if __name__ == '__main__':
main()
```
Problem is, I already get a syntax error at the module import line:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "encoder.py", line 98
SyntaxError: invalid syntax
```

Your help would be appreciated, @SpotlightKid .

**Comment by SpotlightKid** [comment]
Unfortunately I introduced a syntax error through a typo in line 98, when I changed the `reset` method three months ago. This is fixed now in b42db78.
