### ISSUE TITLE
Trouble Installing / Building

### ISSUE THREAD

**Issue by wobafett** [SpotlightKid/micropython-stm-lib#3]
Hi, sorry if this is not the right format for this - I'm learning to use an ESP32 and using micropython and I wanted to use your midi modules! Unfortunately, I can't get this package to install either with PIP or by manually building it into a .bin - any suggestions? Thank you!

**Comment by SpotlightKid** [comment]
Sorry, this package is not ready to be installed with upip. You need to copy the necessary files to the ESP32 manually.

For example with rshell:

```sh
# change to whatever serial port your ESP is connected to
export RSHELL_PORT=/dev/ttyUSB0  
rshell mkdir /pyboard/midi
rshell cp midi/midiin.py /pyboard/midi
rshell cp midi/midiout.py /pyboard/midi
rshell cp midi/constants.py /pyboard/midi
```

You can also compile the Python modules with `mpy-cross` and and copy the resulting `*.mpy` files instead.

On the ESP32 use the modules with e.g. `from midi.midiout import MidiOut`.
